feeds=[
{'feed':'Labor Law Articles (Traditional)','rss':'http://feeds.feedburner.com/LaborLawArticlestraditional'},
{'feed':'Immigration Law Articles','rss':'http://feeds.feedburner.com/ImmigrationLawArticles'},
{'feed':'Federal Employment Law Articles','rss':'http://www.hedgefundlawblog.com/feed'},
{'feed':'Hedge Fund Law Blog','rss':'http://www.hedgefundlawblog.com/feed'},
{'feed':'UN News Centre | Law','rss':' Crime Prevention"','rss':'http://www.un.org/apps/news/rss/rss_law.asp'},
{'feed':'Within the Law at PennLive.com','rss':'http://blog.pennlive.com/within-law/atom.xml'},
{'feed':'Medical Law Review | Current issue','rss':'http://medlaw.oxfordjournals.org/rss/current.xml'},
{'feed':'Securities Compliance & Arbitration - New Jersey Law Blog','rss':'http://www.njlawblog.com/articles/securities-compliance-arbitrat/index.xml'},
{'feed':'OUT-LAW News','rss':'http://www.out-law.com/feeds/out-law-rss'},
{'feed':'New Jersey Law Blog','rss':'http://feeds.lexblog.com/NewJerseyLawBlog'},
{'feed':'Justia Docket Search | Filed in the Alabama Middle District Court','rss':'http://dockets.justia.com/search.py?query=&stateorcourt=court-almdce&l=&mode=rss'},
{'feed':'AboutLawsuits.com | News','rss':'http://feeds.feedburner.com/aboutlawsuits?format=xml'},
{'feed':'Law.com | Newswire','rss':'http://www.law.com/jsp/rss/rss_newswire.jsp'},
{'feed':'Law.com | Small Firm Business','rss':'http://www.law.com/jsp/rss/rss_sfb.jsp'},
{'feed':'Law.com | In-House Counsel','rss':'http://www.law.com/jsp/rss/rss_ihc.jsp'},
{'feed':'LawMemo.com | Arbitration','rss':'http://www.lawmemo.com/arb/memo/atom.xml'},
{'feed':'LawMemo.com | Employment Law 101','rss':'http://www.lawmemo.com/101/atom.xml'},
{'feed':'LawMemo.com | Arbitration Blog','rss':'http://www.lawmemo.com/arbitrationblog/atom.xml'},
{'feed':'LawMemo.com | Employment Law Blog','rss':'http://www.lawmemo.com/blog/atom.xml'},
{'feed':'Law360 | Energy','rss':'http://www.law360.com/appellate/rss'},
{'feed':'Law360 | Intellectual Property','rss':'http://www.law360.com/ip/rss'},
{'feed':'Law360 | Product Liability','rss':'http://www.law360.com/productliability/rss'},
{'feed':'Law360 | Appellate','rss':'http://www.law360.com/appellate/rss'},
{'feed':'Law360 | Environmental','rss':'http://www.law360.com/environmental/rss'},
{'feed':'Law360 | Securities','rss':'http://www.law360.com/securities/rss'},
{'feed':'Legal Talk Network | Law News and Legal Topics','rss':'http://legaltalknetwork.com/RSS/LTN_feed.xml'},
{'feed':'Legal Talk Network | Lawyer2Lawyer | Law News and Legal Topics','rss':'http://legaltalknetwork.com/RSS/C2C_feed.xml'},
{'feed':'Legal Talk Network | Ringler Radio | Structured Settlements and Legal Topics','rss':'http://legaltalknetwork.com/RSS/RR_feed.xml'},
{'feed':'ABA Journal | Top Stories','rss':'http://feeds.feedburner.com/abajournal/topstories'},
{'feed':'ABA Journal | Daily News','rss':'http://feeds.feedburner.com/abajournal/dailynews'},
{'feed':'ABA Journal | Magazine Stories','rss':'http://feeds.feedburner.com/abajournal/magazine'},
{'feed':'ABA Journal | Legal Rebels','rss':'http://feeds.feedburner.com/LegalRebels'},
{'feed':'ABA Journal | Business of Law','rss':'http://www.abajournal.com/topics/rss/C827'},
{'feed':'ABA Journal | Law in Popular Culture','rss':'http://www.abajournal.com/topics/rss/C778'},
{'feed':'Legal Week | All News','rss':'http://www.legalweek.com/feeds/rss/type/news'},
{'feed':'Legal Week | All Articles','rss':'http://www.legalweek.com/feeds/rss'},
{'feed':'LegalWeekLaw | Arbitration','rss':'http://www.legalweeklaw.com/browse/755/feeds/rss/practice-area/litigation-and-dispute-resolution/arbitration?page=1&per_page=10'},
{'feed':'Lawyers and Settlements :: Hot Issues','rss':'http://www.lawyersandsettlements.com/rss/hot.xml'},
{'feed':'Lawyers and Settlements :: Latest Cases & Settlements','rss':'http://www.lawyersandsettlements.com/rss/main.xml'},
{'feed':'Lawyers and Settlements :: Jane Mundys Articles','rss':'http://www.lawyersandsettlements.com/rss/articles.xml'},
{'feed':'Lawyers and Settlements :: Drugs/Medical','rss':'http://www.lawyersandsettlements.com/rss/Drugs%2CMedical.xml'},
{'feed':'Lawyers and Settlements :: Civil/Human Rights','rss':'http://www.lawyersandsettlements.com/rss/Civil%2CHuman%20Rights.xml'},
{'feed':'Lawyers and Settlements :: Automotive','rss':'http://www.lawyersandsettlements.com/rss/Automotive.xml'},
{'feed':'Lawyers and Settlements :: Antitrust','rss':'http://www.lawyersandsettlements.com/rss/Antitrust.xml'},
{'feed':'Lawyers and Settlements | Whistleblower','rss':'http://www.lawyersandsettlements.com/rss/Whistleblower.xml'},
{'feed':'Lawyers and Settlements | Media/Telecom','rss':'http://www.lawyersandsettlements.com/rss/Media%2CTelecom.xml'},
{'feed':'Federal Employment Law Articles','rss':'http://feeds.feedburner.com/EmploymentLawArticles'},
{'feed':'California Employment Law Articles','rss':'http://feeds.feedburner.com/CaliforniaEmploymentLawArticles'},
{'feed':'Florida Employment Law Articles','rss':'http://feeds.feedburner.com/FloridaEmploymentLawArticles'},
{'feed':'Indiana Employment Law Articles','rss':'http://feeds.feedburner.com/IndianaEmploymentLawArticles'},
{'feed':'Maryland Employment Law Articles','rss':'http://feeds.feedburner.com/MarylandEmploymentLawArticles'},
{'feed':'Massachusetts Employment Law Articles','rss':'http://feeds.feedburner.com/MassachusettsEmploymentLawArticles'},
{'feed':'Michigan Employment Law Articles','rss':'http://feeds.feedburner.com/MichiganEmploymentLawArticles'},
{'feed':'New Jersey Employment Law Articles','rss':'http://feeds.feedburner.com/NewJerseyEmploymentLawArticles'},
{'feed':'New York Employment Law Articles','rss':'http://feeds.feedburner.com/elinfonet/MSYW'},
{'feed':'Oregon Employment Law Articles','rss':'http://feeds.feedburner.com/OregonEmploymentLawArticles'},
{'feed':'Pennsylvania Employment Law Articles','rss':'http://feeds.feedburner.com/PennsylvaniaEmploymentLawArticles'},
{'feed':'South Carolina Employment Law Articles','rss':'http://feeds.feedburner.com/SouthCarolinaEmploymentLawArticles'},
{'feed':'Tennessee Employment Law Articles','rss':'http://feeds.feedburner.com/TennesseeEmploymentLawArticles'},
{'feed':'Texas Employment Law Articles','rss':'http://feeds.feedburner.com/TexasEmploymentLawArticles'},
{'feed':'Virginia Employment Law Articles','rss':'http://feeds.feedburner.com/VirginiaEmploymentLawArticles'},
{'feed':'Washington State Employment Law Articles','rss':'http://feeds.feedburner.com/WashingtonStateEmploymentLawArticles'},
{'feed':'Wisconsin Employment Law Articles','rss':'http://feeds.feedburner.com/WisconsinEmploymentLawArticles'}
]

