feeds=[
    {"feed":"Lawyers and Settlements :: Hot Issues","rss":"http://www.lawyersandsettlements.com/rss/hot.xml","category":"Trade / Industry"},
{"feed":"AustralianIT.com.au | Law / PoliticsFeed","rss":"http://feeds.news.com.au/public/rss/2.0/ausit_law_-_politics_5.xml","category":"Trade / Industry"},
{"feed":"Lawyers and Settlements :: Antitrust","rss":"http://www.lawyersandsettlements.com/rss/Antitrust.xml","category":"Trade / Industry"},
{"feed":"Lawyers and Settlements :: Latest Cases & Settlements","rss":"http://www.lawyersandsettlements.com/rss/main.xml","category":"Trade / Industry"},
{"feed":"Lawyers and Settlements :: Drugs/Medical","rss":"http://www.lawyersandsettlements.com/rss/Drugs%2CMedical.xml","category":"Trade / Industry"},
{"feed":"Lawyers and Settlements :: Jane Mundy's Articles","rss":"http://www.lawyersandsettlements.com/rss/articles.xml","category":"Trade / Industry"},
{"feed":"OUT-LAW News","rss":"http://www.out-law.com/feeds/out-law_roundup.aspx","category":"Trade / Industry"},
{"feed":"Lawyers and Settlements :: Civil/Human Rights","rss":"http://www.lawyersandsettlements.com/rss/Civil%2CHuman%20Rights.xml","category":"Trade / Industry"},
{"feed":"CDC's Public Health Law News","rss":"http://www2a.cdc.gov/phlp/rss/cdcs_public_health_law_news.xml","category":"Regulatory / Government"},
{"feed":"Lawyers and Settlements :: Automotive","rss":"http://www.lawyersandsettlements.com/rss/Automotive.xml","category":"Trade / Industry"},
{"feed":"Billboard.biz | Legal Management Industry News","rss":"http://feeds.feedburner.com/billboard/vEpK","category":"Trade / Industry"},
{"feed":"Bytestart: Legal & People","rss":"http://www.bytestart.co.uk/content/affiliate/legal.rss","category":"Topical"},
{"feed":"??????? ???????????????? ????????","rss":"http://www.priorbank.by/r/service/rss.aspx?rq=20&channel=53&news=r/news/law","category":"Company"},
{"feed":"New Jersey Law Blog","rss":"http://feeds.lexblog.com/NewJerseyLawBlog","category":"Blog / Online Forum"},
{"feed":"news.gov.hk | Law & Order","rss":"http://www.news.gov.hk/rss/news/lawandorder_en.xml","category":"Regulatory / Government"},
{"feed":"NewsHour with Jim Lehrer | Law Coverage | PBS","rss":"http://www.pbs.org/newshour/rss/law.xml","category":"Broadcast / General"},
{"feed":"Long Island Business News | Law","rss":"http://libn.com/blog/category/news/law/feed","category":"Topical"},
{"feed":"CPSC | Recent Recalls and Product Safety News","rss":"http://www.cpsc.gov/cpscpub/prerel/prerel.xml","category":"Regulatory / Government"},
{"feed":"PopularMechanics.com | Military & Law Enforcement","rss":"http://feeds.popularmechanics.com/pm/technology/military_law/","category":"Magazine"},
{"feed":"WSJ.com | Law","rss":"http://online.wsj.com/xml/rss/3_7091.xml","category":"Financial"},
{"feed":"AEI.Org | Legal and Constitutional Studies","rss":"http://www.aei.org/ra/30?presentation=rss","category":"Not-For-Profit / NGO"},
{"feed":"Bracewell & Giuliani | News Releases","rss":"http://www.bracewellgiuliani.com/rss/feat_news_releases.xml","category":"Company"},
{"feed":"Federal Employment Law Articles","rss":"http://feeds.feedburner.com/EmploymentLawArticles","category":"Regulatory / Government"},
{"feed":"Network World on Lawsuits","rss":"http://www.networkworld.com/rss/lawsuits.xml","category":"Trade / Industry"},
{"feed":"Lawyering Articles","rss":"http://feeds.feedburner.com/LawyeringArticles","category":"Regulatory / Government"},
{"feed":"Securities Compliance & Arbitration - New Jersey Law Blog","rss":"http://www.njlawblog.com/articles/securities-compliance-arbitrat/index.xml","category":"Blog / Online Forum"},
{"feed":"Employment Law Verdicts | Discrimination Verdicts","rss":"http://feeds.feedburner.com/EmploymentLawVerdicts-DiscriminationVerdicts","category":"Regulatory / Government"},
{"feed":"Massachusetts Employment Law Articles","rss":"http://feeds.feedburner.com/MassachusettsEmploymentLawArticles","category":"Regulatory / Government"},
{"feed":"Michigan Employment Law Articles","rss":"http://feeds.feedburner.com/MichiganEmploymentLawArticles","category":"Regulatory / Government"},
{"feed":"New Jersey Employment Law Articles","rss":"http://feeds.feedburner.com/NewJerseyEmploymentLawArticles","category":"Regulatory / Government"},
{"feed":"South Carolina Employment Law Articles","rss":"http://feeds.feedburner.com/SouthCarolinaEmploymentLawArticles","category":"Regulatory / Government"},
{"feed":"CCH News | Work Week","rss":"http://research.cch.com/Windlass/RssNews.aspx?Page=21&Section=1&Title=CCH%20News:%20Work%20Week","category":"Topical"},
{"feed":"CCH News | Safety/OSHA","rss":"http://research.cch.com/Windlass/RssNews.aspx?Page=44&Section=1&Title=%20CCH%20News:%20Safety/OSHA","category":"Topical"},
{"feed":"Latin American Legal Sector","rss":"http://www.latinbusinesschronicle.com/rss/latinlaw/","category":"Financial"},
{"feed":"CCH News | Unemployment Insurance with Social Security","rss":"http://research.cch.com/Windlass/RssNews.aspx?Page=25&Section=1&Title=%20CCH%20News:%20Unemployment%20Insurance%20with%20Social%20Security","category":"Topical"},
{"feed":"Uspharmacist | Pharmacy Law","rss":"http://www.uspharmacist.com/desktopmodules/Jobson.Modules.CMS.UI.USP/usprss.aspx?d=pharmacy_law","category":"Trade / Industry"},
{"feed":"Medical Law Review | Current issue","rss":"http://medlaw.oxfordjournals.org/rss/current.xml","category":"Academic / Research"},
{"feed":"UN News Centre | Law, Crime Prevention","rss":"http://www.un.org/apps/news/rss/rss_law.asp","category":"Not-For-Profit / NGO"},
{"feed":"WSJ.com | Law Blog","rss":"http://blogs.wsj.com/law/feed/","category":"Blog / Online Forum"},
{"feed":"Justia Docket Search | Filed in the Alabama Southern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-alsdce&l=&mode=rss","category":"Court"},
{"feed":"Hedge Fund Law Blog","rss":"http://www.hedgefundlawblog.com/feed","category":"Blog / Online Forum"},
{"feed":"Within the Law at PennLive.com","rss":"http://blog.pennlive.com/within-law/atom.xml","category":"Blog / Online Forum"},
{"feed":"Immigration Law Articles","rss":"http://feeds.feedburner.com/ImmigrationLawArticles","category":"Regulatory / Government"},
{"feed":"Justia Docket Search | Filed in Alaska","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-ak&l=&mode=rss","category":"Court"},
{"feed":"WebWire | News by Industry | Class Actions / Lawsuits","rss":"http://rssfeeds.webwire.com/WebWire-News-Class-Actions-Lawsuits","category":"Press Release"},
{"feed":"Labor Law Articles (Traditional)","rss":"http://feeds.feedburner.com/LaborLawArticlestraditional","category":"Regulatory / Government"},
{"feed":"Justia Docket Search | Filed in the California Eastern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-caedce&l=&mode=rss","category":"Court"},
{"feed":"CAMLAW | Complementary And Alternative Medicine Law Blog","rss":"http://www.camlawblog.com/index.rdf","category":"Blog / Online Forum"},
{"feed":"California Employment Law Articles","rss":"http://feeds.feedburner.com/CaliforniaEmploymentLawArticles","category":"Regulatory / Government"},
{"feed":"Justia Docket Search | Filed in the California Northern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-candce&l=&mode=rss","category":"Court"},
{"feed":"Indiana Employment Law Articles","rss":"http://feeds.feedburner.com/IndianaEmploymentLawArticles","category":"Regulatory / Government"},
{"feed":"Maryland Employment Law Articles","rss":"http://feeds.feedburner.com/MarylandEmploymentLawArticles","category":"Regulatory / Government"},
{"feed":"Florida Employment Law Articles","rss":"http://feeds.feedburner.com/FloridaEmploymentLawArticles","category":"Regulatory / Government"},
{"feed":"Texas Employment Law Articles","rss":"http://feeds.feedburner.com/TexasEmploymentLawArticles","category":"Regulatory / Government"},
{"feed":"Washington State Employment Law Articles","rss":"http://feeds.feedburner.com/WashingtonStateEmploymentLawArticles","category":"Regulatory / Government"},
{"feed":"New York Employment Law Articles","rss":"http://feeds.feedburner.com/elinfonet/MSYW","category":"Regulatory / Government"},
{"feed":"Law.com | Corporate Counsel","rss":"http://www.law.com/jsp/rss/rss_corpcounsel.jsp","category":"Topical"},
{"feed":"Oregon Employment Law Articles","rss":"http://feeds.feedburner.com/OregonEmploymentLawArticles","category":"Regulatory / Government"},
{"feed":"Pennsylvania Employment Law Articles","rss":"http://feeds.feedburner.com/PennsylvaniaEmploymentLawArticles","category":"Regulatory / Government"},
{"feed":"Tennessee Employment Law Articles","rss":"http://feeds.feedburner.com/TennesseeEmploymentLawArticles","category":"Regulatory / Government"},
{"feed":"Virginia Employment Law Articles","rss":"http://feeds.feedburner.com/VirginiaEmploymentLawArticles","category":"Regulatory / Government"},
{"feed":"Wisconsin Employment Law Articles","rss":"http://feeds.feedburner.com/WisconsinEmploymentLawArticles","category":"Regulatory / Government"},
{"feed":"CCH News | Human Resources Management","rss":"http://research.cch.com/Windlass/RssNews.aspx?Page=22&Section=1&Title=CCH%20News:%20Human%20Resources%20Management","category":"Topical"},
{"feed":"Justia Docket Search | Filed in the Florida Northern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-flndce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Georgia Southern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-gasdce&l=&mode=rss","category":"Court"},
{"feed":"CCH News | Pension and Benefits","rss":"http://research.cch.com/Windlass/RssNews.aspx?Page=24&Section=1&Title=%20CCH%20News:%20Pension%20and%20Benefits","category":"Topical"},
{"feed":"CCH News | Payroll","rss":"http://research.cch.com/Windlass/RssNews.aspx?Page=23&Section=1&Title=%20CCH%20News:%20Payroll","category":"Topical"},
{"feed":"Justia Docket Search | Filed in Hawaii","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-hi&l=&mode=rss","category":"Court"},
{"feed":"Sedgwick Press Releases","rss":"https://www.sedgwickcms.com/rss/sedgwickcms.xml","category":"Company"},
{"feed":"Lawyers and Settlements | Whistleblower","rss":"http://www.lawyersandsettlements.com/rss/Whistleblower.xml","category":"Trade / Industry"},
{"feed":"Justia Docket Search | Filed in the Kentucky Eastern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-kyedce&l=&mode=rss","category":"Court"},
{"feed":"Biznespolska | Wroc?awski Przegl?d Prasy","rss":"http://www.biznespolska.pl/rss/prasa_wroclaw.xml","category":"Topical"},
{"feed":"CNW Group | Legal","rss":"http://rss.newswire.ca/en/newswire/rls_law_en.xml?99C19F26E73111DD97D6AE68B1B1FDF9","category":"Newswire"},
{"feed":"Justia Docket Search | Filed in the Louisiana Eastern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-laedce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Alabama Northern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-alndce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Louisiana Western District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-lawdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in Massachusetts","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-ma&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the California Southern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-casdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Michigan Western District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-miwdce&l=&mode=rss","category":"Court"},
{"feed":"Business Law Prof Blog","rss":"http://lawprofessors.typepad.com/business_law/atom.xml","category":"Blog / Online Forum"},
{"feed":"Justia Docket Search | Filed in the Mississippi Southern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-mssdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in Colorado","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-co&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Missouri Western District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-mowdce&l=&mode=rss","category":"Court"},
{"feed":"Lawyers and Settlements | Media/Telecom","rss":"http://www.lawyersandsettlements.com/rss/Media%2CTelecom.xml","category":"Trade / Industry"},
{"feed":"Justia Docket Search | Filed in New Jersey","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-nj&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the New York Eastern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-nyedce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in Connecticut","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-ct&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Alabama Middle District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-almdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the North Carolina Eastern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-ncedce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Oklahoma Eastern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-okedce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Oklahoma Western District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-okwdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in Rhode Island","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-ri&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Texas Northern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-txndce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Virginia Eastern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-vaedce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Virginia Western District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-vawdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Washington Eastern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-waedce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Washington Western District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-wawdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the West Virginia Northern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-wvndce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Wisconsin Western District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-wiwdc&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in Puerto Rico","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-pr&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Bankruptcy Category","rss":"http://dockets.justia.com/search.py?query=&lawsuittype=noscat-9&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in Delaware","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-de&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Florida Southern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-flsdce&l=&mode=rss","category":"Court"},
{"feed":"Am Law Daily | Blog","rss":"http://amlawdaily.typepad.com/amlawdaily/index.rdf","category":"Blog / Online Forum"},
{"feed":"Justia Docket Search | Filed in the Georgia Middle District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-gamdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in Arizona","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-az&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Georgia Northern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-gandce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Arkansas Eastern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-aredce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Illinois Central District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-ilcdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Illinois Northern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-ilndce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Indiana Northern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-inndce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Kentucky Western District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-kywdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in Maryland","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-md&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Arkansas Western District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-arwdce&l=&mode=rss","category":"Court"},
{"feed":"Davis Polk & Wardwell | Antitrust","rss":"http://www.davispolk.com/rss/rss.aspx?id=3","category":"Company"},
{"feed":"Justia Docket Search | Filed in the California Central District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-cacdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in District of Columbia","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-dc&l=&mode=rss","category":"Court"},
{"feed":"Davis Polk & Wardwell | Insolvency & Restructuring","rss":"http://www.davispolk.com/rss/rss.aspx?id=10","category":"Company"},
{"feed":"Justia Docket Search | Filed in the Michigan Eastern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-miedce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Florida Middle District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-flmdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Mississippi Northern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-msndce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in Idaho","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-id&l=&mode=rss","category":"Court"},
{"feed":"Bracewell & Giuliani | Energy Legal Blog","rss":"http://feeds2.feedburner.com/EnergyLegalBlog","category":"Blog / Online Forum"},
{"feed":"Justia Docket Search | Filed in the Missouri Eastern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-moedce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Illinois Southern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-ilsdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in Montana","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-mt&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Indiana Southern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-insdce&l=&mode=rss","category":"Court"},
{"feed":"BCBR.com | Legal & Courts","rss":"http://www.bcbr.com/rss/industry.asp?cid=12","category":"Regional / Local"},
{"feed":"Justia Docket Search | Filed in the New York Southern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-nysdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Iowa Northern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-iandce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Iowa Southern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-iasdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the North Carolina Western District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-ncwdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in Kansas","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-ks&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in North Dakota","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-nd&l=&mode=rss","category":"Court"},
{"feed":"Davis Polk & Wardwell | China","rss":"http://www.davispolk.com/rss/rss.aspx?id=18","category":"Company"},
{"feed":"Justia Docket Search | Filed in the Louisiana Middle District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-lamdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Ohio Northern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-ohndce&l=&mode=rss","category":"Court"},
{"feed":"Kelley Drye & Warren | Bankruptcy and Restructuring","rss":"http://www.kelleydrye.com/rss/rss.xml?practicePath=/practices/bankruptcy_restructuring/21","category":"Company"},
{"feed":"Justia Docket Search | Filed in Maine","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-me&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in Oregon","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-or&l=&mode=rss","category":"Court"},
{"feed":"Kelley Drye & Warren | Consumer Class Action Defense","rss":"http://www.kelleydrye.com/rss/rss.xml?practicePath=/practices/advertising_marketing/consumer_class_action_defense/40","category":"Company"},
{"feed":"Justia Docket Search | Filed in Minnesota","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-mn&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Tennessee Western District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-tnwdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Texas Eastern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-txedce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Texas Southern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-txsdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Texas Western District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-txwdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in Nebraska","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-ne&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the West Virginia Southern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-wvsdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in Nevada","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-nv&l=&mode=rss","category":"Court"},
{"feed":"Cooley | Events","rss":"http://www.cooley.com/files/event.xml","category":"Company"},
{"feed":"Justia Docket Search | Filed in Guam","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-gu&l=&mode=rss","category":"Court"},
{"feed":"Blakes | Press Releases","rss":"http://www.blakes.com/IN/rss.asp?mode=cate&CID=210#","category":"Company"},
{"feed":"Justia Docket Search | Filed in New Hampshire","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-nh&l=&mode=rss","category":"Court"},
{"feed":"Blakes | Legal Articles","rss":"http://www.blakes.com/IN/rss.asp?mode=cate&CID=10","category":"Company"},
{"feed":"Justia Docket Search | Filed in the New York Southern District Court in the Securities/Commodities/Exchanges Category","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-nysdce&lawsuittype=nos-850&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in New Mexico","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-nm&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the New York Northern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-nyndce&l=&mode=rss","category":"Court"},
{"feed":"K&L Gates | Bid Protest Law","rss":"http://feeds.lexblog.com/BidProtestLaw","category":"Blog / Online Forum"},
{"feed":"Justia Docket Search | Filed in the New York Western District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-nywdce&l=&mode=rss","category":"Court"},
{"feed":"DWT | Appellate Litigation","rss":"http://www.dwt.com/Advisories.rss?filter=58216&feedName=Advisories","category":"Company"},
{"feed":"Justia Docket Search | Filed in the North Carolina Middle District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-ncmdce&l=&mode=rss","category":"Court"},
{"feed":"DWT | Arbitration","rss":"http://www.dwt.com/Advisories.rss?filter=58222&feedName=Advisories","category":"Company"},
{"feed":"Justia Docket Search | Filed in the Ohio Southern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-ohsdce&l=&mode=rss","category":"Court"},
{"feed":"DWT | Banking & Financial Services","rss":"http://www.dwt.com/Advisories.rss?filter=58172&feedName=Advisories","category":"Company"},
{"feed":"Justia Docket Search | Filed in the Oklahoma Northern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-okndce&l=&mode=rss","category":"Court"},
{"feed":"DWT | Commercial Speech & Advertising","rss":"http://www.dwt.com/Advisories.rss?filter=57091&feedName=Advisories","category":"Company"},
{"feed":"Crowell | Press Releases","rss":"http://www.crowell.com/Global/RSS.aspx?type=PRESSRELEASES","category":"Company"},
{"feed":"Justia Docket Search | Filed in the Pennsylvania Eastern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-paedce&l=&mode=rss","category":"Court"},
{"feed":"DWT | Corporate Finance & Securities","rss":"http://www.dwt.com/Advisories.rss?filter=58151&feedName=Advisories","category":"Company"},
{"feed":"Davis Polk & Wardwell | Mergers & Aquisitions","rss":"http://www.davispolk.com/rss/rss.aspx?id=13","category":"Company"},
{"feed":"Justia Docket Search | Filed in the Pennsylvania Middle District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-pamdce&l=&mode=rss","category":"Court"},
{"feed":"DWT | Credit Recovery & Bankruptcy","rss":"http://www.dwt.com/Advisories.rss?filter=58166&feedName=Advisories","category":"Company"},
{"feed":"Justia Docket Search | Filed in the Pennsylvania Western District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-pawdce&l=&mode=rss","category":"Court"},
{"feed":"Davis Polk & Wardwell | Energy/Utilities","rss":"http://www.davispolk.com/rss/rss.aspx?id=16","category":"Company"},
{"feed":"Justia Docket Search | Filed in South Carolina","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-sc&l=&mode=rss","category":"Court"},
{"feed":"Hogan Lovells | All News","rss":"http://www.hoganlovells.com/rss/rss.aspx?id=46","category":"Company"},
{"feed":"Justia Docket Search | Filed in South Dakota","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-sd&l=&mode=rss","category":"Court"},
{"feed":"DWT | Defamation & Privacy","rss":"http://www.dwt.com/Advisories.rss?filter=57093&feedName=Advisories","category":"Company"},
{"feed":"Corporate Finance | O'Melveny & Myers","rss":"http://www.omm.com/rss/rss.aspx?id=6","category":"Company"},
{"feed":"DWT | Digital Media","rss":"http://www.dwt.com/Advisories.rss?filter=17420&feedName=Advisories","category":"Company"},
{"feed":"DWT | E-Discovery","rss":"http://www.dwt.com/Advisories.rss?filter=58219&feedName=Advisories","category":"Company"},
{"feed":"Davis Polk & Wardwell | Corporate Governance","rss":"http://www.davispolk.com/rss/rss.aspx?id=6","category":"Company"},
{"feed":"DWT | Electric Power","rss":"http://www.dwt.com/Advisories.rss?filter=56773&feedName=Advisories","category":"Company"},
{"feed":"Davis Polk & Wardwell | Environmental","rss":"http://www.davispolk.com/rss/rss.aspx?id=7","category":"Company"},
{"feed":"DWT | Emerging Companies","rss":"http://www.dwt.com/Advisories.rss?filter=58154&feedName=Advisories","category":"Company"},
{"feed":"DWT | Employee Benefits","rss":"http://www.dwt.com/Advisories.rss?filter=58141&feedName=Advisories","category":"Company"},
{"feed":"DWT | Employment Counseling","rss":"http://www.dwt.com/Advisories.rss?filter=58191&feedName=Advisories","category":"Company"},
{"feed":"DWT | Franchising","rss":"http://www.dwt.com/Advisories.rss?filter=64456&feedName=Advisories","category":"Company"},
{"feed":"DWT | Health Care Business & Transactions","rss":"http://www.dwt.com/Advisories.rss?filter=58294&feedName=Advisories","category":"Company"},
{"feed":"DWT | Health Care Reform","rss":"http://www.dwt.com/Advisories.rss?filter=264493&feedName=Advisories","category":"Company"},
{"feed":"DWT | Patent","rss":"http://www.dwt.com/Advisories.rss?filter=58178&feedName=Advisories","category":"Company"},
{"feed":"DWT | Trusts and Estates","rss":"http://www.dwt.com/Advisories.rss?filter=79105&feedName=Advisories","category":"Company"},
{"feed":"Davis Polk & Wardwell | Executive Compensation & Employee Benefits","rss":"http://www.davispolk.com/rss/rss.aspx?id=8","category":"Company"},
{"feed":"DWT | Wireless","rss":"http://www.dwt.com/Advisories.rss?filter=148684&feedName=Advisories","category":"Company"},
{"feed":"Davis Polk & Wardwell | London","rss":"http://www.davispolk.com/RSSOffice.aspx?office=5","category":"Company"},
{"feed":"Kelley Drye & Warren | Broker-Dealer","rss":"http://www.kelleydrye.com/rss/rss.xml?practicePath=/practices/broker_dealer/02","category":"Company"},
{"feed":"Kelley Drye & Warren | Campaign Finance and Political Law","rss":"http://www.kelleydrye.com/rss/rss.xml?practicePath=/practices/government_relations_public_policy/campaign_finance_political_law/54","category":"Company"},
{"feed":"Kelley Drye & Warren | Corporate","rss":"http://www.kelleydrye.com/rss/rss.xml?practicePath=/practices/corporate/04","category":"Company"},
{"feed":"Justia Docket Search | Filed in the Tennessee Eastern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-tnedce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Tennessee Middle District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-tnmdce&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in Utah","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-ut&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in Vermont","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-vt&l=&mode=rss","category":"Court"},
{"feed":"Justia Docket Search | Filed in the Wisconsin Eastern District Court","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=court-wiedce&l=&mode=rss","category":"Court"},
{"feed":"Kelley Drye & Warren | Corporate Finance and Securities","rss":"http://www.kelleydrye.com/rss/rss.xml?practicePath=/practices/corporate_finance_securities/22","category":"Company"},
{"feed":"Law.com | Newswire","rss":"http://www.law.com/jsp/rss/rss_newswire.jsp","category":"Topical"},
{"feed":"Kelley Drye & Warren | Employee Benefits and Executive Compensation","rss":"http://www.kelleydrye.com/rss/rss.xml?practicePath=/practices/employee_benefits_executive_compensation/05","category":"Company"},
{"feed":"Kelley Drye & Warren | Environmental Law","rss":"http://www.kelleydrye.com/rss/rss.xml?practicePath=/practices/environmental_law/06","category":"Company"},
{"feed":"Kelley Drye & Warren | Food and Drug Law","rss":"http://www.kelleydrye.com/rss/rss.xml?practicePath=/practices/food_drug_law/33","category":"Company"},
{"feed":"Justia Docket Search | Filed in Wyoming","rss":"http://dockets.justia.com/search.py?query=&stateorcourt=state-wy&l=&mode=rss","category":"Court"},
{"feed":"Kelley Drye & Warren | Government Relations and Public Policy","rss":"http://www.kelleydrye.com/rss/rss.xml?practicePath=/practices/government_relations_public_policy/35","category":"Company"},
{"feed":"Justia Docket Search | Filed in the Federal Tax Suits Category","rss":"http://dockets.justia.com/search.py?query=&lawsuittype=noscat-12&l=&mode=rss","category":"Court"},
{"feed":"Cooley | Reports and Published Articles","rss":"http://www.cooley.com/files/articles.xml","category":"Company"},
{"feed":"Alcohol / Addiction / Illegal Drugs News From Medical News Today","rss":"http://www.medicalnewstoday.com/rss/alcohol-addiction-illegal_drugs.xml","category":"Topical"},
{"feed":"Baker Donelson | Events","rss":"http://www.bakerdonelson.com/rss/rss.aspx?id=1","category":"Company"},
{"feed":"Blakes | Legal Bulletins ","rss":"http://www.blakes.com/IN/rss.asp?mode=cate&CID=249#","category":"Company"},
{"feed":"AboutLawsuits.com | News","rss":"http://feeds.feedburner.com/aboutlawsuits?format=xml","category":"Blog / Online Forum"},
{"feed":"Law.com | Small Firm Business","rss":"http://www.law.com/jsp/rss/rss_sfb.jsp","category":"Topical"},
{"feed":"All Dorsey Publications","rss":"http://www.dorsey.com/rss/rss.aspx?id=16","category":"Company"},
{"feed":"DWT | Banking","rss":"http://www.dwt.com/Advisories.rss?filter=17433&feedName=Advisories","category":"Company"},
{"feed":"Davis Polk & Wardwell | Capital Markets","rss":"http://www.davispolk.com/rss/rss.aspx?id=5","category":"Company"},
{"feed":"DWT | Business Transactions","rss":"http://www.dwt.com/Advisories.rss?filter=58129&feedName=Advisories","category":"Company"},
{"feed":"Davis Polk & Wardwell | Intellectual Property","rss":"http://www.davispolk.com/rss/rss.aspx?id=11","category":"Company"},
{"feed":"DWT | Cable","rss":"http://www.dwt.com/Advisories.rss?filter=17419&feedName=Advisories","category":"Company"},
{"feed":"Davis Polk & Wardwell | Litigation","rss":"http://www.davispolk.com/rss/rss.aspx?id=14","category":"Company"},
{"feed":"Squire Sanders | All Press Releases","rss":"http://www.ssd.com/rss/rss.aspx?id=2","category":"Company"},
{"feed":"Davis Polk & Wardwell | Investment Management","rss":"http://www.davispolk.com/rss/rss.aspx?id=12","category":"Company"},
{"feed":"DWT | Class Action Defense","rss":"http://www.dwt.com/Advisories.rss?filter=58220&feedName=Advisories","category":"Company"},
{"feed":"Davis Polk & Wardwell | Tax","rss":"http://www.davispolk.com/rss/rss.aspx?id=15","category":"Company"},
{"feed":"Davis Polk & Wardwell | Asia","rss":"http://www.davispolk.com/rss/rss.aspx?id=17","category":"Company"},
{"feed":"Kelley Drye & Warren | Press Releases","rss":"http://www.kelleydrye.com/rss/rss.xml?searchPath=/news/press_releases&searchStructure=resource","category":"Company"},
{"feed":"DWT | Government Financing","rss":"http://www.dwt.com/Advisories.rss?filter=58169&feedName=Advisories","category":"Company"},
{"feed":"Kelley Drye & Warren | Advertising and Marketing","rss":"http://www.kelleydrye.com/rss/rss.xml?practicePath=/practices/advertising_marketing/32","category":"Company"},
{"feed":"Kelley Drye & Warren | Consumer Product Safety","rss":"http://www.kelleydrye.com/rss/rss.xml?practicePath=/practices/consumer_product_safety/34","category":"Company"},
{"feed":"Kelley Drye & Warren | Europe","rss":"http://www.kelleydrye.com/rss/rss.xml?practicePath=/practices/international/europe/13","category":"Company"},
{"feed":"DWT | Government Regulation of Content","rss":"http://www.dwt.com/Advisories.rss?filter=57102&feedName=Advisories","category":"Company"},
{"feed":"Kelley Drye & Warren | Export Controls and Compliance","rss":"http://www.kelleydrye.com/rss/rss.xml?practicePath=/practices/international_trade_customs/export_controls_economic_sanctions/55","category":"Company"},
{"feed":"DWT | Health Care","rss":"http://www.dwt.com/Advisories.rss?filter=17412&feedName=Advisories","category":"Company"},
{"feed":"DWT | Health Care Operations","rss":"http://www.dwt.com/Advisories.rss?filter=58298&feedName=Advisories","category":"Company"},
{"feed":"Kelley Drye & Warren | FTC and State AG Investigations","rss":"http://www.kelleydrye.com/rss/rss.xml?practicePath=/practices/advertising_marketing/ftc_state_ag_investigations/41","category":"Company"},
{"feed":"Kelley Drye & Warren | Financial Institutions","rss":"http://www.kelleydrye.com/rss/rss.xml?practicePath=/practices/financial_institutions/07","category":"Company"},
{"feed":"DWT | Mergers & Acquisitions","rss":"http://www.dwt.com/Advisories.rss?filter=58156&feedName=Advisories","category":"Company"},
{"feed":"DWT | Privacy & Security","rss":"http://www.dwt.com/Advisories.rss?filter=58139&feedName=Advisories","category":"Company"},
{"feed":"DWT | Renewable Energy","rss":"http://www.dwt.com/Advisories.rss?filter=17426&feedName=Advisories","category":"Company"},
{"feed":"DWT | State and Local Tax","rss":"http://www.dwt.com/Advisories.rss?filter=58205&feedName=Advisories","category":"Company"},
{"feed":"DWT | Tax","rss":"http://www.dwt.com/Advisories.rss?filter=58131&feedName=Advisories","category":"Company"},
{"feed":"Law.com | Newswire","rss":"http://www.law.com/jsp/rss/rss_newswire.jsp","category":"Topical"},
{"feed":"Law.com | Small Firm Business","rss":"http://www.law.com/jsp/rss/rss_sfb.jsp","category":"Topical"},
{"feed":"Daily Record | Local news","rss":"http://lawdailyrecord.com/16_rss.xml","category":"Regional / Local"},
{"feed":"Cooley | Press Releases","rss":"http://www.cooley.com/files/pressreleases.xml","category":"Company"},
{"feed":"Law.com | In-House Counsel","rss":"http://www.law.com/jsp/rss/rss_ihc.jsp","category":"Topical"},
{"feed":"Law.com | Legal Blog Watch","rss":"http://legalblogwatch.typepad.com/legal_blog_watch/atom.xml","category":"Blog / Online Forum"},
{"feed":"Cooley | In the News","rss":"http://www.cooley.com/files/inthenews.xml","category":"Company"},
{"feed":"Baker Donelson | News","rss":"http://www.bakerdonelson.com/rss/rss.aspx?id=2","category":"Company"},
{"feed":"DWT | Access to Public Records & Proceedings","rss":"http://www.dwt.com/Advisories.rss?filter=57089&feedName=Advisories","category":"Company"},
{"feed":"DWT | Advertising, Marketing & Promotions","rss":"http://www.dwt.com/Advisories.rss?filter=17401&feedName=Advisories","category":"Company"},
{"feed":"DWT | Agribusiness","rss":"http://www.dwt.com/Advisories.rss?filter=17402&feedName=Advisories","category":"Company"},
{"feed":"DWT | Antitrust","rss":"http://www.dwt.com/Advisories.rss?filter=58215&feedName=Advisories","category":"Company"},
{"feed":"DWT | China","rss":"http://www.dwt.com/Advisories.rss?filter=17404&feedName=Advisories","category":"Company"},
{"feed":"DWT | Communications, Media & Technology","rss":"http://www.dwt.com/Advisories.rss?filter=17405&feedName=Advisories","category":"Company"},
{"feed":"DWT | Complex Commercial Litigation","rss":"http://www.dwt.com/Advisories.rss?filter=58209&feedName=Advisories","category":"Company"},
{"feed":"DWT | Construction","rss":"http://www.dwt.com/Advisories.rss?filter=17406&feedName=Advisories","category":"Company"},
{"feed":"DWT | Employment Class Actions","rss":"http://www.dwt.com/Advisories.rss?filter=58188&feedName=Advisories","category":"Company"},
{"feed":"DWT | Entertainment","rss":"http://www.dwt.com/Advisories.rss?filter=17409&feedName=Advisories","category":"Company"},
{"feed":"DWT | Environmental & Natural Resources","rss":"http://www.dwt.com/Advisories.rss?filter=58287&feedName=Advisories","category":"Company"},
{"feed":"DWT | Federal Tax","rss":"http://www.dwt.com/Advisories.rss?filter=58207&feedName=Advisories","category":"Company"},
{"feed":"DWT | Film","rss":"http://www.dwt.com/Advisories.rss?filter=17428&feedName=Advisories","category":"Company"},
{"feed":"DWT | Finance and Commercial Transactions","rss":"http://www.dwt.com/Advisories.rss?filter=58130&feedName=Advisories","category":"Company"},
{"feed":"DWT | Health Care Clinical Research & Intellectual Property","rss":"http://www.dwt.com/Advisories.rss?filter=58295&feedName=Advisories","category":"Company"},
{"feed":"DWT | Health Care Finance","rss":"http://www.dwt.com/Advisories.rss?filter=58296&feedName=Advisories","category":"Company"},
{"feed":"DWT | Health Care Regulation & Compliance","rss":"http://www.dwt.com/Advisories.rss?filter=58292&feedName=Advisories","category":"Company"},
{"feed":"DWT | Health Care Reimbursement & Payment","rss":"http://www.dwt.com/Advisories.rss?filter=58299&feedName=Advisories","category":"Company"},
{"feed":"DWT | Intellectual Property","rss":"http://www.dwt.com/Advisories.rss?filter=58133&feedName=Advisories","category":"Company"},
{"feed":"DWT | Internet and E-Commerce","rss":"http://www.dwt.com/Advisories.rss?filter=17414&feedName=Advisories","category":"Company"},
{"feed":"DWT | Labor","rss":"http://www.dwt.com/Advisories.rss?filter=58187&feedName=Advisories","category":"Company"},
{"feed":"DWT | Payment Card Agreements & Payment Systems","rss":"http://www.dwt.com/Advisories.rss?filter=17434&feedName=Advisories","category":"Company"},
{"feed":"DWT | Real Estate","rss":"http://www.dwt.com/Advisories.rss?filter=17421&feedName=Advisories","category":"Company"},
{"feed":"DWT | Software & Technology","rss":"http://www.dwt.com/Advisories.rss?filter=61301&feedName=Advisories","category":"Company"},
{"feed":"DWT | Telecommunications","rss":"http://www.dwt.com/Advisories.rss?filter=17423&feedName=Advisories","category":"Company"},
{"feed":"DWT | Trademark","rss":"http://www.dwt.com/Advisories.rss?filter=58177&feedName=Advisories","category":"Company"},
{"feed":"Bizjournals.com | Legal Services News","rss":"http://feeds.bizjournals.com/industry_14?format=xml","category":"Financial"},
{"feed":"Building | Legal news","rss":"http://www.building.co.uk/XmlServers/navsectionRSS.aspx?navsectioncode=696","category":"Trade / Industry"},
{"feed":"Connecticut Employment Law Blog","rss":"http://feeds.lexblog.com/ConnecticutEmploymentLawBlog","category":"Blog / Online Forum"},
{"feed":"Work Matters | Employment Law Blog","rss":"http://texaslawyer.typepad.com/work_matters/rss.xml","category":"Blog / Online Forum"},
{"feed":"Legal Satyricon | Blog","rss":"http://randazza.wordpress.com/feed/","category":"Blog / Online Forum"},
{"feed":"Volokh Conspiracy | Blog","rss":"http://feeds.feedburner.com/volokh/mainfeed","category":"Blog / Online Forum"},
{"feed":"Connecticut Law Blog","rss":"http://aconnecticutlawblog.com/feed/","category":"Blog / Online Forum"},
{"feed":"Lowering the Bar | Legal Humor Blog","rss":"http://feeds.feedburner.com/LoweringTheBar","category":"Blog / Online Forum"},
{"feed":"WK News - FERC - Opinions, orders, decisions, newsletters","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_15765/xxx?user=MBElLwH78VYs4gLuZX3Wq8ZZl/O5IkP9&da=WKUS_TAL_15765","category":"Independent"},
{"feed":"Sheppard Mullin Richter and Hampton | China Law Update","rss":"http://feeds.lexblog.com/SMRHChinaLawBlog","category":"Blog / Online Forum"},
{"feed":"Law.com | Technology News","rss":"http://www.law.com/jsp/rss/rss_lawtechnologynews.jsp","category":"Topical"},
{"feed":"BLT | Law and Lobbying Blog","rss":"http://legaltimes.typepad.com/blt/rss.xml","category":"Blog / Online Forum"},
{"feed":"Brian Leiter | Law School Reports","rss":"http://feeds.feedburner.com/BrianLeitersLawSchoolReports","category":"Blog / Online Forum"},
{"feed":"Delaware Employment Law Blog","rss":"http://feeds.feedburner.com/delawareemploymentlawblog/UagR","category":"Blog / Online Forum"},
{"feed":"Jonathan Turley | Blog","rss":"http://jonathanturley.org/feed/","category":"Blog / Online Forum"},
{"feed":"Bow Tie Law's Blog","rss":"http://bowtielaw.wordpress.com/feed/","category":"Blog / Online Forum"},
{"feed":"European Court of Human Rights | Press Releases","rss":"http://cmiskp.echr.coe.int/rss/pr-en-all.xml","category":"Court"},
{"feed":"Coal Age | Legally Speaking","rss":"http://www.coalage.com/index.php/departments/legally-speaking.feed?type=rss","category":"Magazine"},
{"feed":"Law.com | Daily Business Review | Articles","rss":"http://www.law.com/jsp/law/rss_dbr.jsp","category":"Topical"},
{"feed":"PLC | US Finance","rss":"http://usfinance.practicallaw.com/rss.do","category":"Independent"},
{"feed":"WK News | EEOC Compliance Manual Newsletters","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_5033/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_5033","category":"Independent"},
{"feed":"WK News | Financial & Estate Planning Ideas & Trends","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_1866/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_1866","category":"Independent"},
{"feed":"BD Law Blog ","rss":"http://www.bdlawblog.com/atom.xml","category":"Blog / Online Forum"},
{"feed":"Conglomerate Blog","rss":"http://feeds.feedburner.com/theconglomerate/feed","category":"Blog / Online Forum"},
{"feed":"3 Geeks and a Law | Blog","rss":"http://feeds.feedburner.com/geeklawblog","category":"Company"},
{"feed":"WK News | State Inheritance, Estate and Gift Tax Report Letter","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_4808/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_4808","category":"Independent"},
{"feed":"Bizjournals.com | Legal Services News","rss":"http://feeds.bizjournals.com/industry_14?format=xml","category":"Financial"},
{"feed":"WK News | State Employment Law Newsletters","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_5128/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_5128","category":"Independent"},
{"feed":"WK News | Labor Law Reports: Insight Newsletters","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_1875/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_1875","category":"Independent"},
{"feed":"Building | Legal news","rss":"http://www.building.co.uk/XmlServers/navsectionRSS.aspx?navsectioncode=696","category":"Trade / Industry"},
{"feed":"Connecticut Employment Law Blog","rss":"http://feeds.lexblog.com/ConnecticutEmploymentLawBlog","category":"Blog / Online Forum"},
{"feed":"WK News | LLC Advisor Newsletter","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_1524/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_1524","category":"Independent"},
{"feed":"Work Matters | Employment Law Blog","rss":"http://texaslawyer.typepad.com/work_matters/rss.xml","category":"Blog / Online Forum"},
{"feed":"WK News | Federal Excise Tax Report Letter","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_1891/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_1891","category":"Independent"},
{"feed":"WK News | Tax Treaties Report Letters","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_8269/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_8269","category":"Independent"},
{"feed":"Law.com | Texas Lawyer","rss":"http://www.law.com/jsp/rss/rss_tx.jsp","category":"Trade / Industry"},
{"feed":"WK News | CCH State Employment Law Tracker","rss":"http://intelliconnect.cch.com/mantle-public/rss/x?userId=293067","category":"Newswire"},
{"feed":"Oblon | ITC Law Blog","rss":"http://www.itcblog.com/feed/","category":"Blog / Online Forum"},
{"feed":"Legal Satyricon | Blog","rss":"http://randazza.wordpress.com/feed/","category":"Blog / Online Forum"},
{"feed":"Volokh Conspiracy | Blog","rss":"http://feeds.feedburner.com/volokh/mainfeed","category":"Blog / Online Forum"},
{"feed":"Connecticut Law Blog","rss":"http://aconnecticutlawblog.com/feed/","category":"Blog / Online Forum"},
{"feed":"ABA Journal | Top Stories","rss":"http://feeds.feedburner.com/abajournal/topstories","category":"Trade / Industry"},
{"feed":"ABA Journal | Magazine Stories","rss":"http://feeds.feedburner.com/abajournal/magazine","category":"Trade / Industry"},
{"feed":"ABA Journal | Legal Ethics","rss":"http://www.abajournal.com/topics/rss/C127","category":"Trade / Industry"},
{"feed":"Lowering the Bar | Legal Humor Blog","rss":"http://feeds.feedburner.com/LoweringTheBar","category":"Blog / Online Forum"},
{"feed":"WK News - FERC - Opinions, orders, decisions, newsletters","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_15765/xxx?user=MBElLwH78VYs4gLuZX3Wq8ZZl/O5IkP9&da=WKUS_TAL_15765","category":"Independent"},
{"feed":"ABANow | Top Stories","rss":"http://www.abanow.org/category/top-stories/feed/rss/","category":"Not-For-Profit / NGO"},
{"feed":"ABANow | Around the Bar","rss":"http://www.abanow.org/category/around-the-bar/feed/rss/","category":"Not-For-Profit / NGO"},
{"feed":"Bankruptcy Litigation Blog","rss":"http://feeds.lexblog.com/BankruptcyLitigationBlog","category":"Aggregated Research"},
{"feed":"Delaware Business Bankruptcy Report","rss":"http://feeds.lexblog.com/DelawareBusinessBankruptcyReport","category":"Blog / Online Forum"},
{"feed":"China Law and Practice | Banking & Finance","rss":"http://www.chinalawandpractice.com/RSS.aspx?FeedID=424","category":"Trade / Industry"},
{"feed":"SCOTUSblog","rss":"http://www.scotusblog.com/feed/","category":"Blog / Online Forum"},
{"feed":"Blue Sky Law Reporter | Report Letter ","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_1674/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_1674","category":"Independent"},
{"feed":"U.S. 4th Circuit Court | Opinions","rss":"http://pacer.ca4.uscourts.gov/rss/OpinionsReleased.rss","category":"Court"},
{"feed":"U.S. 5th Circuit Court |  Opinions","rss":"http://www.ca5.uscourts.gov/Rss.aspx?Feed=Opinions&Which=All&Style=Detail","category":"Court"},
{"feed":"U.S. 8th Circuit Court | Opinions","rss":"http://www.ca8.uscourts.gov/rss/ca8opns_rss.xml","category":"Court"},
{"feed":"USCADC | Recent Opinions","rss":"http://www.cadc.uscourts.gov/internet/opinions.nsf/uscadcopinions.xml","category":"Court"},
{"feed":"SCOTUS | Argument Transcripts","rss":"http://www.supremecourt.gov/rss/argument_transcripts_rss.aspx","category":"Court"},
{"feed":"Committee of Advertising Practice | Latest news","rss":"http://www.cap.org.uk/RSS-Feeds/News-Feed.aspx","category":"Not-For-Profit / NGO"},
{"feed":"Altman Weil Connect","rss":"http://connect.altmanweil.com/?feed=rss2","category":"Blog / Online Forum"},
{"feed":"TalkLeft","rss":"http://feeds.feedburner.com/TalkleftThePoliticsOfCrime","category":"Blog / Online Forum"},
{"feed":"WK News | Federal Estate and Gift Tax Report Letter","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_1723/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_1723","category":"Independent"},
{"feed":"WK News | Labor Arbitration Awards Newsletters","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_2083/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_2083","category":"Independent"},
{"feed":"CPSC | Recent Child-Related Product Recalls","rss":"http://www.cpsc.gov/cpscpub/prerel/prerelchild.xml","category":"Regulatory / Government"},
{"feed":"WK News | Pension Plan Guide Newsletter","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_1495/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_1495","category":"Independent"},
{"feed":"CPSC | Recent Outdoor Product-Related Recalls","rss":"http://www.cpsc.gov/cpscpub/prerel/prereloutdoor.xml","category":"Regulatory / Government"},
{"feed":"CPSC | Recent Sports/Recreation Related Recalls","rss":"http://www.cpsc.gov/cpscpub/prerel/prerelrecreation.xml","category":"Regulatory / Government"},
{"feed":"WK News | Labor Relations and Wages-Hours Newsletters","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_1874/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_1874","category":"Independent"},
{"feed":"Baker & McKenzie | Global Newsroom","rss":"http://www.bakermckenzie.com/rsslisting/rss.aspx?id=3","category":"Company"},
{"feed":"Davis Polk & Wardwell | Publications","rss":"http://www.davispolk.com/rss/rss.aspx?id=2","category":"Company"},
{"feed":"WK News | Partnership Tax Watch Newsletter","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_1526/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_1526","category":"Independent"},
{"feed":"USDOJ | Criminal Division Intellectual Property Press Releases","rss":"http://www.cybercrime.gov/ippress.xml","category":"Regulatory / Government"},
{"feed":"WK News | State Business Credits & Incentives Alert","rss":"http://intelliconnect.cch.com/mantle-public/rss/x?userId=1184610","category":"Newswire"},
{"feed":"American Libraries Magazine | AL Direct","rss":"http://feeds.feedburner.com/americanlibrariesmagazine/KocJ","category":"Blog / Online Forum"},
{"feed":"Oblon | Patents Post Grant Blog","rss":"http://www.patentspostgrant.com/lang/en/feed","category":"Blog / Online Forum"},
{"feed":"American Libraries Magazine | E-Content Blog","rss":"http://americanlibrariesmagazine.org/e-content/rss.xml","category":"Blog / Online Forum"},
{"feed":"WK News | OFCCP Manual Newsletters","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_5027/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_5027","category":"Independent"},
{"feed":"WK News | Affordable Care Act News","rss":"http://intelliconnect.cch.com/mantle-public/rss/x?userId=2062728","category":"Newswire"},
{"feed":"ABA Journal | Business of Law","rss":"http://www.abajournal.com/topics/rss/C827","category":"Trade / Industry"},
{"feed":"ABA Journal | Law in Popular Culture","rss":"http://www.abajournal.com/topics/rss/C778","category":"Trade / Industry"},
{"feed":"American Libraries Magazine | Solutions and Services","rss":"http://feeds.feedburner.com/AmericanLibrariesSolutionsAndServices","category":"Trade / Industry"},
{"feed":"ABA Journal | Litigation","rss":"http://www.abajournal.com/topics/rss/C95","category":"Trade / Industry"},
{"feed":"ABA Journal | Work/Life Balance","rss":"http://www.abajournal.com/topics/rss/C207","category":"Trade / Industry"},
{"feed":"Davis Polk & Wardwell | Financial Institutions","rss":"http://www.davispolk.com/rss/rss.aspx?id=9","category":"Company"},
{"feed":"ABANow | Releases","rss":"http://www.abanow.org/category/releases/feed/rss/","category":"Not-For-Profit / NGO"},
{"feed":"ABANow | ABA in the News","rss":"http://www.abanow.org/category/aba_in_the_news/feed/rss/","category":"Not-For-Profit / NGO"},
{"feed":"Squire Sanders | Triage Blog","rss":"http://feeds.lexblog.com/TriageHealthLawBlog","category":"Blog / Online Forum"},
{"feed":"WK News | Labor Law Journal","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_17016/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_17016","category":"Independent"},
{"feed":"WK News | Federal Banking Law Reporter - Report Letter","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_1679/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_1679","category":"Independent"},
{"feed":"ABANow | Commentary","rss":"http://www.abanow.org/category/releases/commentary/feed/rss/","category":"Not-For-Profit / NGO"},
{"feed":"Business Bankruptcy Blog","rss":"http://feeds.lexblog.com/BusinessBankruptcyBlog","category":"Blog / Online Forum"},
{"feed":"WK News | Corporate Secretary's Answer Book Update Notification","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_35163/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_35163","category":"Independent"},
{"feed":"Wragge & Co | News","rss":"http://feeds.feedburner.com/WraggeCoWraggeNews","category":"Company"},
{"feed":"Federal Judiciary | News","rss":"http://www.uscourts.gov/rss/InsideTheJudiciary.rss","category":"Court"},
{"feed":"California Biotech Law Blog","rss":"http://californiabiotechlaw.com/feed/","category":"Blog / Online Forum"},
{"feed":"FindLaw | Law and Daily Life","rss":"http://feeds.findlaw.com/LawAndLife?format=xml","category":"Blog / Online Forum"},
{"feed":"U.S. Court of Appeals for the Federal Circuit | Opinions & Orders","rss":"http://www.cafc.uscourts.gov/rss-opinions.php","category":"Court"},
{"feed":"U.S. 3rd Circuit Court | Opinions","rss":"http://www.ca3.uscourts.gov/recentop/week/recopinions.xml","category":"Court"},
{"feed":"DLA Piper International | US Publications","rss":"http://www.dlapiper.com/rsslisting/rss.aspx?id=25","category":"Company"},
{"feed":"U.S. 9th Circuit Court | Opinions","rss":"http://www.ca9.uscourts.gov/feed/opinions.xml","category":"Court"},
{"feed":"Irwin Mitchell | News","rss":"http://www.irwinmitchell.com/_layouts/IrwinMitchell/NewsFeed.ashx","category":"Company"},
{"feed":"Hogan Lovells | Financial Institutions Group","rss":"http://www.hoganlovells.com/rss/rss.aspx?id=15","category":"Company"},
{"feed":"Withers | Latest News","rss":"http://www.withersworldwide.com/feeds/publications/news","category":"Company"},
{"feed":"Field Fisher Waterhouse | Events","rss":"http://www.ffw.com/events/eventfeed.ashx","category":"Company"},
{"feed":"USDOJ | Criminal Division Press Releases","rss":"http://www.justice.gov/rss/rss.crm.hp.xml","category":"Regulatory / Government"},
{"feed":"USDOJ | Criminal Division Cybercrime Press Releases","rss":"http://www.cybercrime.gov/allpress.xml","category":"Regulatory / Government"},
{"feed":"Shoosmiths | Commercial","rss":"http://feeds.feedburner.com/ShoosmithsCommercialLegalUpdates?format=xml","category":"Company"},
{"feed":"Shoosmiths | People Issues","rss":"http://feeds.feedburner.com/ShoosmithsEmploymentLegalUpdates?format=xml","category":"Company"},
{"feed":"USDOJ | Criminal Division Deepwater Horizon (BP) Oil-Spill Fraud","rss":"http://www.justice.gov/criminal/oilspill/pr/oilspill.fraud.xml","category":"Regulatory / Government"},
{"feed":"American Libraries Magazine | Ask the ALA Librarian","rss":"http://feeds.feedburner.com/AskTheAlaLibrarianBlog","category":"Blog / Online Forum"},
{"feed":"Hill Dickinson | News","rss":"http://www.hilldickinson.com/feeds/news_feed.aspx","category":"Company"},
{"feed":"Berrymans Lace Mawer | News","rss":"http://www.blm-law.com/rss/news/","category":"Company"},
{"feed":"American Libraries Magazine | Updates","rss":"http://www.americanlibrariesmagazine.org/rss.xml","category":"Trade / Industry"},
{"feed":"Mills & Reeve | Events","rss":"http://www.mills-reeve.com/rss/rss.aspx?id=3","category":"Company"},
{"feed":"Charles Russell | Latest News","rss":"http://www.charlesrussell.co.uk/rss.ashx?rsstype=Latest-News&type=Latest-News","category":"Company"},
{"feed":"Burges Salmon | News","rss":"http://www.burges-salmon.com/news/news.xml","category":"Company"},
{"feed":"Lawrence Graham | Blogs IP","rss":"http://lgblogsip.lg-legal.com/lgblogsip.rss.ashx","category":"Blog / Online Forum"},
{"feed":"Davis Polk & Wardwell | Corporate Governance Blog","rss":"http://www.davispolk.com/briefing/corporategovernance/?view=rss","category":"Blog / Online Forum"},
{"feed":"Medica | News","rss":"http://medicalnet.ro/feed/","category":"Topical"},
{"feed":"Baker Donelson | Events, Publications and News","rss":"http://www.bakerdonelson.com/rss/rss.aspx?id=4","category":"Company"},
{"feed":"Stiri.com.ro | Medicina","rss":"http://www.stiri.com.ro/rss/sanatate/medicina/","category":"Regional / Local"},
{"feed":"Squire Sanders | Anticorruption Blog","rss":"http://feeds.lexblog.com/AnticorruptionBlog","category":"Blog / Online Forum"},
{"feed":"SNR Denton | Publications","rss":"http://www.snrdenton.com/feeds/publications.ashx","category":"Company"},
{"feed":"WK News | State Tax Review","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_13456/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_13456","category":"Independent"},
{"feed":"WK News | CCH Federal Tax Weekly","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_508/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_508","category":"Independent"},
{"feed":"Kilpatrick Stockton | Events","rss":"http://www.kilpatricktownsend.com/en/Knowledge_Center/Events.aspx?device=rss","category":"Company"},
{"feed":"Kilpatrick Stockton | Alerts & Podcasts","rss":"http://www.kilpatricktownsend.com/en/Knowledge_Center/Alerts_and_Podcasts.aspx?device=rss","category":"Company"},
{"feed":"PLC | Corporate and Securities","rss":"http://uscorporate.practicallaw.com/rss.do","category":"Independent"},
{"feed":"Altman Weil Cotterman on Compensation","rss":"http://blog.altmanweil.com/feed/","category":"Blog / Online Forum"},
{"feed":"Kilpatrick Stockton | Publications","rss":"http://www.kilpatricktownsend.com/en/Knowledge_Center/Publications.aspx?device=rss","category":"Company"},
{"feed":"WK News | Corporation Report Bulletin","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_13055/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_13055","category":"Independent"},
{"feed":"Squire Sanders | Sixth Circuit Appellate Blog","rss":"http://feeds.lexblog.com/6thCircuitAppellateBlog","category":"Blog / Online Forum"},
{"feed":"Instapundit","rss":"http://pajamasmedia.com/instapundit/feed/","category":"Blog / Online Forum"},
{"feed":"CCH Employment Law Daily | News","rss":"http://www.employmentlawdaily.com/index.php/feed/","category":"Independent"},
{"feed":"Snell & Wilmer | News","rss":"http://feeds.feedburner.com/swlaw/in-the-news?format=xml","category":"Company"},
{"feed":"Delaware Corporate and Commercial Litigation Blog","rss":"http://feeds.feedburner.com/DelawareCorporateAndCommercialLitigationBlog","category":"Blog / Online Forum"},
{"feed":"WK News | State Employment Law Decisions Newsletters","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_5129/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_5129","category":"Independent"},
{"feed":"Nelson Mullins | Newsletters","rss":"http://www.nelsonmullins.com/rss/rss_newsletters.cfm","category":"Company"},
{"feed":"Wiley Rein | News Releases","rss":"http://www.wileyrein.com/rss/news_releases/rss.xml","category":"Company"},
{"feed":"WK News | Employment Practices Guide Newsletters","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_1726/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_1726","category":"Independent"},
{"feed":"WK News | Secured Transactions Guide - Report Letter","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_1798/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_1798","category":"Independent"},
{"feed":"DealLawyers.com Blog","rss":"http://www.deallawyers.com/Blog/atom.xml","category":"Blog / Online Forum"},
{"feed":"WK News | S Corporations Guide Report Letter","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_1528/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_1528","category":"Independent"},
{"feed":"WK News | Multistate Corporate Income Tax Review","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_14931/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_14931","category":"Independent"},
{"feed":"WK News | Corporate Finance and the Securities Laws Update Notification","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_35281/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_35281","category":"Independent"},
{"feed":"Wiley Rein | Events","rss":"http://www.wileyrein.com/rss/events/rss.xml","category":"Company"},
{"feed":"WK News | Patent Claim Construction Update Notification","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_35213/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_35213","category":"Independent"},
{"feed":"WK News | America Invents Act: Law and Analysis Update Notification","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_17072/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_17072","category":"Independent"},
{"feed":"Stoel Rives | Press Releases","rss":"http://www.stoel.com/RSS.aspx?Type=PressReleases","category":"Company"},
{"feed":"WK News | Benefits Law Journal","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_12918/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_12918","category":"Independent"},
{"feed":"Sedgwick | Client Bulletins","rss":"https://www.sedgwickcms.com/rss/clientbulletin.xml","category":"Company"},
{"feed":"Sedgwick | Leave Law Updates","rss":"https://www.sedgwickcms.com/rss/leavelaws.xml","category":"Company"},
{"feed":"Corante | Between Lawyers Blog","rss":"http://feeds.feedburner.com/BetweenLawyers","category":"Blog / Online Forum"},
{"feed":"WK News | Patent Claim Construction Update Notification","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_35213/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_35213","category":"Independent"},
{"feed":"Irwin Mitchell | Business News","rss":"http://www.irwinmitchell.com/_layouts/IrwinMitchell/BusinessNewsFeed.ashx","category":"Company"},
{"feed":"Field Fisher Waterhouse | Publications","rss":"http://www.ffw.com/publications/publicationfeed.ashx","category":"Company"},
{"feed":"Shoosmiths | Intellectual Property","rss":"http://feeds.feedburner.com/IntellectualPropertyLegalUpdatesFromShoosmiths?format=xml","category":"Company"},
{"feed":"WK News | America Invents Act: Law and Analysis Update Notification","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_17072/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_17072","category":"Independent"},
{"feed":"Baker & McKenzie | Global Newsroom","rss":"http://www.bakermckenzie.com/rsslisting/rss.aspx?id=3","category":"Company"},
{"feed":"Davis Polk & Wardwell | Publications","rss":"http://www.davispolk.com/rss/rss.aspx?id=2","category":"Company"},
{"feed":"WK News | Benefits Law Journal","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_12918/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_12918","category":"Independent"},
{"feed":"Corante | Between Lawyers Blog","rss":"http://feeds.feedburner.com/BetweenLawyers","category":"Blog / Online Forum"},
{"feed":"MVA Library  | Lloyds","rss":"http://extranet.mvalaw.com/library/category/lloyds/feed/","category":"Independent"},
{"feed":"Shoosmiths | IT Legal Updates","rss":"http://feeds.feedburner.com/ShoosmithsTechnology?format=xml","category":"Company"},
{"feed":"Shoosmiths | Preventing and Resolving Disputes","rss":"http://feeds.feedburner.com/ShoosmithsPreventingAndResolvingDisputesLegalUpdates?format=xml","category":"Company"},
{"feed":"LinkLaters | Publications","rss":"http://www.linklaters.com/Utility/rss.ashx?site=Publications","category":"Company"},
{"feed":"LinkLaters | Seminars","rss":"http://www.linklaters.com/Utility/rss.ashx?site=Seminars","category":"Company"},
{"feed":"USDOJ | Criminal Division Intellectual Property Press Releases","rss":"http://www.cybercrime.gov/ippress.xml","category":"Regulatory / Government"},
{"feed":"American Libraries Magazine | AL Direct","rss":"http://feeds.feedburner.com/americanlibrariesmagazine/KocJ","category":"Blog / Online Forum"},
{"feed":"American Libraries Magazine | E-Content Blog","rss":"http://americanlibrariesmagazine.org/e-content/rss.xml","category":"Blog / Online Forum"},
{"feed":"Shoosmiths | Real Estate","rss":"http://feeds.feedburner.com/ShoosmithsPropertyLegalUpdates?format=xml","category":"Company"},
{"feed":"Shoosmiths | Social Housing","rss":"http://feeds.feedburner.com/ShoosmithsSocialHousingLegalUpdates?format=xml","category":"Company"},
{"feed":"DLA Piper International | Product Liability","rss":"http://www.dlapiper.com/rsslisting/rss.aspx?id=27","category":"Company"},
{"feed":"American Libraries Magazine | Solutions and Services","rss":"http://feeds.feedburner.com/AmericanLibrariesSolutionsAndServices","category":"Trade / Industry"},
{"feed":"DLA Piper International | News and Publications for PLA","rss":"http://www.dlapiper.com/rsslisting/rss.aspx?id=24","category":"Company"},
{"feed":"Shoosmiths | Press Release","rss":"http://feeds.feedburner.com/ShoosmithsPressReleaseRssFeed?format=xml","category":"Company"},
{"feed":"Berrymans Lace Mawer | Events","rss":"http://www.blm-law.com/rss/events/","category":"Company"},
{"feed":"Hogan Lovells | All Publications","rss":"http://www.hoganlovells.com/rss/rss.aspx?id=1","category":"Company"},
{"feed":"Mills & Reeve | Publications","rss":"http://www.mills-reeve.com/rss/rss.aspx?id=2","category":"Company"},
{"feed":"Davis Polk & Wardwell | Financial Institutions","rss":"http://www.davispolk.com/rss/rss.aspx?id=9","category":"Company"},
{"feed":"Squire Sanders | Triage Blog","rss":"http://feeds.lexblog.com/TriageHealthLawBlog","category":"Blog / Online Forum"},
{"feed":"WK News | Labor Law Journal","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_17016/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_17016","category":"Independent"},
{"feed":"WK News | Federal Banking Law Reporter - Report Letter","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_1679/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_1679","category":"Independent"},
{"feed":"WK News | Corporate Secretary's Answer Book Update Notification","rss":"http://research.cch.com/RLS/Service.svc/rss/WKUS_TAL_35163/xxx?user=m4Ns58sIedpZYwK1BKnSeOAJaKCBFLRuSAwDQHUUpqs=&da=WKUS_TAL_35163","category":"Independent"},
{"feed":"California Biotech Law Blog","rss":"http://californiabiotechlaw.com/feed/","category":"Blog / Online Forum"},
{"feed":"Charles Russell | Events","rss":"http://www.charlesrussell.co.uk/rss.ashx?rsstype=Events&","category":"Company"},
{"feed":"Hogan Lovells | All Events","rss":"http://www.hoganlovells.com/rss/rss.aspx?id=63","category":"Company"},
{"feed":"FindLaw | Law and Daily Life","rss":"http://feeds.findlaw.com/LawAndLife?format=xml","category":"Blog / Online Forum"},
{"feed":"Clyde & Co | Press releases","rss":"http://www.clydeco.com/feeds/news","category":"Company"},
{"feed":"DLA Piper International | US Publications","rss":"http://www.dlapiper.com/rsslisting/rss.aspx?id=25","category":"Company"},
{"feed":"Nabarro | Latest News","rss":"http://www.nabarro.com/lt_rss.aspx","category":"Company"},
{"feed":"Irwin Mitchell | News","rss":"http://www.irwinmitchell.com/_layouts/IrwinMitchell/NewsFeed.ashx","category":"Company"},
{"feed":"Nabarro | Briefings and Reports","rss":"http://feeds.feedburner.com/NabarroRssBriefingsAndReportsFeed?format=xml","category":"Company"},
{"feed":"Withers | Latest News","rss":"http://www.withersworldwide.com/feeds/publications/news","category":"Company"},
{"feed":"Field Fisher Waterhouse | Events","rss":"http://www.ffw.com/events/eventfeed.ashx","category":"Company"},
{"feed":"Shoosmiths | Commercial","rss":"http://feeds.feedburner.com/ShoosmithsCommercialLegalUpdates?format=xml","category":"Company"},
{"feed":"Field Fisher Waterhouse | Latest news","rss":"http://www.ffw.com/news/newsfeed.ashx","category":"Company"},
{"feed":"Charles Russell | Legal Updates","rss":"http://www.charlesrussell.co.uk/rss.ashx?rsstype=Legal-Updates&type=Legal-Updates","category":"Company"},
{"feed":"Shoosmiths | Compliance Regulatory and Risk","rss":"http://feeds.feedburner.com/ShoosmithsComplianceRegulatoryAndRiskLegalUpdates?format=xml","category":"Company"},
{"feed":"Shoosmiths | People Issues","rss":"http://feeds.feedburner.com/ShoosmithsEmploymentLegalUpdates?format=xml","category":"Company"},
{"feed":"Kilpatrick Stockton | Newsroom","rss":"http://www.kilpatricktownsend.com/en/Knowledge_Center/Newsroom.aspx?device=rss","category":"Company"},
{"feed":"Shoosmiths | Corporate","rss":"http://feeds.feedburner.com/CorporateLegalUpdatesFromShoosmiths?format=xml","category":"Company"},
{"feed":"Kilpatrick Stockton | Experience","rss":"http://www.kilpatricktownsend.com/en/Experience.aspx?device=rss","category":"Company"},
{"feed":"Hill Dickinson | News","rss":"http://www.hilldickinson.com/feeds/news_feed.aspx","category":"Company"},
{"feed":"Berrymans Lace Mawer | News","rss":"http://www.blm-law.com/rss/news/","category":"Company"},
{"feed":"Mills & Reeve | Events","rss":"http://www.mills-reeve.com/rss/rss.aspx?id=3","category":"Company"},
{"feed":"Shoosmiths | Legal Updates","rss":"http://feeds.feedburner.com/ShoosmithsLegalUpdatesRssFeed?format=xml","category":"Company"},
{"feed":"Charles Russell | Latest News","rss":"http://www.charlesrussell.co.uk/rss.ashx?rsstype=Latest-News&type=Latest-News","category":"Company"},
{"feed":"Burges Salmon | News","rss":"http://www.burges-salmon.com/news/news.xml","category":"Company"},
{"feed":"Lawrence Graham | Blogs IP","rss":"http://lgblogsip.lg-legal.com/lgblogsip.rss.ashx","category":"Blog / Online Forum"},
{"feed":"Snell & Wilmer | Events & Seminars ","rss":"http://feeds.feedburner.com/swlaw/events?format=xml","category":"Company"},
{"feed":"Medica | News","rss":"http://medicalnet.ro/feed/","category":"Topical"},
{"feed":"Holland & Hart | Insurance Law Blog","rss":"http://www.insurancelawoutwest.com/rss.xml","category":"Blog / Online Forum"},
{"feed":"Stiri.com.ro | Medicina","rss":"http://www.stiri.com.ro/rss/sanatate/medicina/","category":"Regional / Local"},
{"feed":"Sedgwick | Newsletters","rss":"https://www.sedgwickcms.com/rss/plnewsletter.xml","category":"Company"},
{"feed":"Jackson Walker | News","rss":"http://www.jw.com/rss/firmnews","category":"Company"},
{"feed":"Frost Brown Todd | Events","rss":"http://www.frostbrowntodd.com/feed-EventsFeed.rss","category":"Company"},
{"feed":"Robins, Kaplan, Miller & Ciresi | Featured","rss":"http://www.rkmc.com/rss.aspx","category":"Company"},
{"feed":"Robins, Kaplan, Miller & Ciresi | All New Content","rss":"http://www.rkmc.com/rss.aspx?all=1","category":"Company"},
{"feed":"SNR Denton | Publications","rss":"http://www.snrdenton.com/feeds/publications.ashx","category":"Company"},
{"feed":"PLC | US Labor & Employment","rss":"http://us.practicallaw.com/rss.do?product=uslabor","category":"Independent"},
{"feed":"Kilpatrick Stockton | Events","rss":"http://www.kilpatricktownsend.com/en/Knowledge_Center/Events.aspx?device=rss","category":"Company"},
{"feed":"Kilpatrick Stockton | Alerts & Podcasts","rss":"http://www.kilpatricktownsend.com/en/Knowledge_Center/Alerts_and_Podcasts.aspx?device=rss","category":"Company"},
{"feed":"Ince & Co | Latest News","rss":"http://incelaw.com/rss/news.xml","category":"Company"},
{"feed":"Kilpatrick Stockton | Publications","rss":"http://www.kilpatricktownsend.com/en/Knowledge_Center/Publications.aspx?device=rss","category":"Company"},
{"feed":"Harness Dickey & Pierce | IP Law Blog","rss":"http://feeds.feedburner.com/HDP_Magazine","category":"Blog / Online Forum"},
{"feed":"Banner & Witcoff | News","rss":"http://www.bannerwitcoff.com/rss_news.php","category":"Company"},
{"feed":"Mills & Reeve | News","rss":"http://www.mills-reeve.com/rss/rss.aspx?id=1","category":"Company"},
{"feed":"Intellectual Ventures | IV Insights","rss":"http://www.intellectualventures.com/IVInsights.rss.ashx","category":"Blog / Online Forum"},
{"feed":"Snell & Wilmer | News","rss":"http://feeds.feedburner.com/swlaw/in-the-news?format=xml","category":"Company"},
{"feed":"Intellectual Ventures | Press Releases & News","rss":"http://www.intellectualventures.com/News.rss.ashx","category":"Company"},
{"feed":"The Consumerist | Recent Updates","rss":"http://consumerist.com/index.xml","category":"Blog / Online Forum"},
{"feed":"Nelson Mullins | Newsletters","rss":"http://www.nelsonmullins.com/rss/rss_newsletters.cfm","category":"Company"},
{"feed":"Leiter Reports | A Philosophy Blog","rss":"http://leiterreports.typepad.com/blog/index.rdf","category":"Blog / Online Forum"},
{"feed":"Wiley Rein | News Releases","rss":"http://www.wileyrein.com/rss/news_releases/rss.xml","category":"Company"},
{"feed":"SNR Denton | News & Insights","rss":"http://www.snrdenton.com/feeds/news.ashx","category":"Company"},
{"feed":"Legal Juice","rss":"http://rss.justia.com/LegalJuiceCom","category":"Blog / Online Forum"},
{"feed":"Wiley Rein | Events","rss":"http://www.wileyrein.com/rss/events/rss.xml","category":"Company"},
{"feed":"Stoel Rives | Press Releases","rss":"http://www.stoel.com/RSS.aspx?Type=PressReleases","category":"Company"},
{"feed":"Sedgwick | Client Bulletins","rss":"https://www.sedgwickcms.com/rss/clientbulletin.xml","category":"Company"},
{"feed":"Faegre Baker Daniels | Design Build Board","rss":"http://www.designbuildboard.com/feed/","category":"Blog / Online Forum"},
{"feed":"Sedgwick | Leave Law Updates","rss":"https://www.sedgwickcms.com/rss/leavelaws.xml","category":"Company"},
{"feed":"Nelson Mullins | Articles and Speeches","rss":"http://www.nelsonmullins.com/rss/rss_articles-speeches.cfm","category":"Company"},
{"feed":"PointOfLaw","rss":"http://www.pointoflaw.com/index.xml","category":"Blog / Online Forum"},
{"feed":"Frost Brown Todd | In the News","rss":"http://www.frostbrowntodd.com/feed-NewsFeed.rss","category":"Company"},
{"feed":"Frost Brown Todd | Industry News","rss":"http://www.frostbrowntodd.com/feed-IndustryNewsFeed.rss","category":"Company"},
{"feed":"Nelson Mullins | Press Releases","rss":"http://www.nelsonmullins.com/rss/rss_press.cfm","category":"Company"},
{"feed":"Frost Brown Todd | Press Releases","rss":"http://www.frostbrowntodd.com/feed-PressReleaseFeed.rss","category":"Company"},
{"feed":"Wiley Rein | Publications","rss":"http://www.wileyrein.com/rss/publications/rss.xml","category":"Company"},
{"feed":"Wiley Rein | In The News","rss":"http://www.wileyrein.com/rss/in_the_news/rss.xml","category":"Company"},
{"feed":"Robins, Kaplan, Miller & Ciresi | Press Releases","rss":"http://www.rkmc.com/rss.aspx?related=Press_Room","category":"Company"},
{"feed":"Sterne Kessler | Press Releases","rss":"http://www.skgf.com/rss.php","category":"Company"},
{"feed":"Oblon | Protecting Designs","rss":"http://www.protectingdesigns.com/blog/atom.xml","category":"Blog / Online Forum"},
{"feed":"Banner & Witcoff | Patent Arcade","rss":"http://www.patentarcade.com/feeds/posts/default?alt=rss","category":"Blog / Online Forum"},
{"feed":"Banner & Witcoff | Press Releases","rss":"http://www.bannerwitcoff.com/rss_press.php","category":"Company"},
{"feed":"Fenwick & West | Publications","rss":"http://www.fenwick.com/rss/?cat=3","category":"Company"},
{"feed":"Stoel Rives | Events","rss":"http://www.stoel.com/RSS.aspx?Type=Events","category":"Company"},
{"feed":"Banner & Witcoff | Events","rss":"http://www.bannerwitcoff.com/rss_events.php","category":"Company"},
{"feed":"Epstein Becker | All News","rss":"http://www.ebglaw.com/rss.aspx","category":"Company"},
{"feed":"Stoel Rives | News","rss":"http://www.stoel.com/RSS.aspx?Type=News","category":"Company"},
{"feed":"Frost Brown Todd | Publications","rss":"http://www.frostbrowntodd.com/feed-PubsFeed.rss","category":"Company"},
{"feed":"Epstein Becker | Corporate Services","rss":"http://www.ebglaw.com/rss.aspx?Area=2802","category":"Company"},
{"feed":"Robins, Kaplan, Miller & Ciresi | Events","rss":"http://www.rkmc.com/rss.aspx?cat=Events","category":"Company"},
{"feed":"PLC | Practical Law","rss":"http://uslf.practicallaw.com/rss.do","category":"Independent"},
{"feed":"Gardere Wynne | Press & Publications","rss":"http://www.gardere.com/XMLData/Publications/rssPress%20and%20Publications.xml","category":"Company"},
{"feed":"Moore & Van Allen | News Update","rss":"http://www.mvalaw.com/feed-mvanews.rss","category":"Company"},
{"feed":"Moore & Van Allen | Publications","rss":"http://www.mvalaw.com/feed-publications.rss","category":"Company"},
{"feed":"Oblon | News and Events","rss":"http://www.oblon.com/feeds/latest-stories","category":"Company"},
{"feed":"Oblon | Blog","rss":"http://www.oblon.com/blog/feed","category":"Blog / Online Forum"},
{"feed":"Althouse | Recent Updates","rss":"http://feeds.feedburner.com/althouse/fullfeed","category":"Blog / Online Forum"},
{"feed":"The Cuban Revolution","rss":"http://feeds.feedburner.com/BrianCubansBlog","category":"Blog / Online Forum"},
{"feed":"WK News | HR Compliance Library","rss":"http://intelliconnect.cch.com/mantle-public/rss/x?userId=2263886","category":"Newswire"},
{"feed":"Thompson Coburn | Sweepstakes Blog","rss":"http://www.thompsoncoburn.com/news-and-information/sweepstakes-law-blog/sweepstakes.rss","category":"Blog / Online Forum"},
{"feed":"Epstein Becker | Health Care & Life Sciences","rss":"http://www.ebglaw.com/rss.aspx?Area=2803","category":"Company"},
{"feed":"Vorys, Sater, Seymour and Pease | News","rss":"http://www.vorys.com/feed-Vorys.rss","category":"Company"}]
